# Generated by Django 5.0.2 on 2024-03-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'managed': False, 'verbose_name_plural': 'Class'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'managed': False, 'verbose_name_plural': 'Family'},
        ),
        migrations.AlterModelOptions(
            name='insectsbbox',
            options={'managed': False, 'verbose_name_plural': 'Bounding boxes'},
        ),
        migrations.AlterModelOptions(
            name='insectsimage',
            options={'managed': False, 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='kingdom',
            options={'managed': False, 'verbose_name_plural': 'Kingdom'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name_plural': 'Order'},
        ),
        migrations.AlterModelOptions(
            name='phylum',
            options={'managed': False, 'verbose_name_plural': 'Phylum'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False, 'verbose_name_plural': 'Species'},
        ),
    ]
