# Generated by Django 5.0.2 on 2024-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0004_alter_class_options_alter_family_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('insects_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=200)),
                ('eng_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('morphologic_feature', models.TextField()),
                ('distribution', models.TextField()),
                ('characteristic', models.TextField()),
                ('behavior', models.TextField()),
                ('protection_method', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpeciesNew',
            fields=[
                ('insects_id', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_column='eName', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=200)),
                ('eng_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('morphologic_feature', models.TextField()),
                ('distribution', models.TextField()),
                ('characteristic', models.TextField()),
                ('behavior', models.TextField()),
                ('protection_method', models.TextField()),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'species_new',
                'managed': False,
            },
        ),
    ]
