# Generated by Django 5.0.2 on 2024-04-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0005_request_speciesnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'managed': False, 'verbose_name_plural': 'Class (Lớp)'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'managed': False, 'verbose_name_plural': 'Family (Họ)'},
        ),
        migrations.AlterModelOptions(
            name='genus',
            options={'managed': False, 'verbose_name_plural': 'Genus (Chi)'},
        ),
        migrations.AlterModelOptions(
            name='insectsbbox',
            options={'managed': False, 'verbose_name_plural': 'Nhãn'},
        ),
        migrations.AlterModelOptions(
            name='insectsimage',
            options={'managed': False, 'verbose_name_plural': 'Hình ảnh'},
        ),
        migrations.AlterModelOptions(
            name='kingdom',
            options={'managed': False, 'verbose_name_plural': 'Kingdom (Giới)'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name_plural': 'Order (Bộ)'},
        ),
        migrations.AlterModelOptions(
            name='phylum',
            options={'managed': False, 'verbose_name_plural': 'Phylum (Ngành)'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'managed': False, 'verbose_name_plural': 'Species (Loài)'},
        ),
    ]
