# Generated by Django 5.0.2 on 2024-04-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0006_alter_class_options_alter_family_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpeciesNew',
        ),
    ]
