# Generated by Django 5.0.2 on 2024-08-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0007_delete_speciesnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDesc',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_id', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('verification_count', models.IntegerField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'request_desc',
                'managed': False,
            },
        ),
    ]
