# Generated by Django 5.0.2 on 2025-02-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insects', '0008_requestdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Tài liệu',
                'db_table': 'document',
                'managed': False,
            },
        ),
    ]
